const IMAGES: any = {
    Logo: new URL('../assets/Images/ElectraLogo.svg', import.meta.url).href,
    Barchart: new URL('../assets/Images/bar-chart.svg', import.meta.url).href,
    User: new URL('../assets/Images/user.svg', import.meta.url).href,
    Product: new URL('../assets/Images/product.svg', import.meta.url).href,
    Wallet: new URL('../assets/Images/Wallet.svg', import.meta.url).href,
    Listing: new URL('../assets/Images/Listing.svg', import.meta.url).href,
    Order: new URL('../assets/Images/order.svg', import.meta.url).href,
    Verification: new URL('../assets/Images/Verification.svg', import.meta.url).href,
    Roles: new URL('../assets/Images/Roles.svg', import.meta.url).href,
    FreeModifier: new URL('../assets/Images/FreeModifier.svg', import.meta.url).href,
    Coupons: new URL('../assets/Images/coupons.svg', import.meta.url).href,
    Categories: new URL('../assets/Images/categories.svg', import.meta.url).href,
    EditWebsite: new URL('../assets/Images/EditWebsite.svg', import.meta.url).href,
    HelpCenter: new URL('../assets/Images/HelpCenter.svg', import.meta.url).href,
    Settings: new URL('../assets/Images/Setting.svg', import.meta.url).href,
    coin: new URL('../assets/Images/coin.svg', import.meta.url).href,
    uparrow: new URL('../assets/Images/uparrow.svg', import.meta.url).href,
    downarrow: new URL('../assets/Images/downarrow.svg', import.meta.url).href,
    box: new URL('../assets/Images/box.svg', import.meta.url).href,
    person: new URL('../assets/Images/person.svg', import.meta.url).href,
    Hand: new URL('../assets/Images/Hand.svg', import.meta.url).href,
    Email: new URL('../assets/Images/Email.svg', import.meta.url).href,
    password: new URL('../assets/Images/password.svg', import.meta.url).href,
    eye: new URL('../assets/Images/eye.svg', import.meta.url).href,
}
export default IMAGES