const IMAGES: any = {
    Logo: new URL('../assets/Images/ElectraLogo.svg', import.meta.url).href,
    Barchart: new URL('../assets/Images/bar-chart.svg', import.meta.url).href,
    User: new URL('../assets/Images/user.svg', import.meta.url).href,
    Product: new URL('../assets/Images/product.svg', import.meta.url).href,
    Wallet: new URL('../assets/Images/Wallet.svg', import.meta.url).href,
    Listing: new URL('../assets/Images/Listing.svg', import.meta.url).href,
    Order: new URL('../assets/Images/order.svg', import.meta.url).href,
    Verification: new URL('../assets/Images/Verification.svg', import.meta.url).href,
    Roles: new URL('../assets/Images/Roles.svg', import.meta.url).href,
    FreeModifier: new URL('../assets/Images/FreeModifier.svg', import.meta.url).href,
    Coupons: new URL('../assets/Images/coupons.svg', import.meta.url).href,
    Categories: new URL('../assets/Images/categories.svg', import.meta.url).href,
    EditWebsite: new URL('../assets/Images/EditWebsite.svg', import.meta.url).href,
    HelpCenter: new URL('../assets/Images/HelpCenter.svg', import.meta.url).href,
    Settings: new URL('../assets/Images/Setting.svg', import.meta.url).href,
    coin: new URL('../assets/Images/coin.svg', import.meta.url).href,
    uparrow: new URL('../assets/Images/uparrow.svg', import.meta.url).href,
    downarrow: new URL('../assets/Images/downarrow.svg', import.meta.url).href,
    box: new URL('../assets/Images/box.svg', import.meta.url).href,
    person: new URL('../assets/Images/person.svg', import.meta.url).href,
    Hand: new URL('../assets/Images/Hand.svg', import.meta.url).href,
    Email: new URL('../assets/Images/Email.svg', import.meta.url).href,
    password: new URL('../assets/Images/password.svg', import.meta.url).href,
    eye: new URL('../assets/Images/eye.svg', import.meta.url).href,
    bluebox: new URL('../assets/Images/bluebox.svg', import.meta.url).href,
    bluehamburger: new URL('../assets/Images/bluehamburger.svg', import.meta.url).href,
    ViewArrow: new URL('../assets/Images/ViewArrow.svg', import.meta.url).href,
    Google: new URL('../assets/Images/Google.svg', import.meta.url).href,
    Facebook: new URL('../assets/Images/facebook.svg', import.meta.url).href,
    Twitter: new URL('../assets/Images/twitter.svg', import.meta.url).href,
    Apple: new URL('../assets/Images/apple.svg', import.meta.url).href,
    Dots: new URL('../assets/Images/dots.svg', import.meta.url).href,
    Iphone1: new URL('../assets/Images/Iphone1.svg', import.meta.url).href,
    Iphone2: new URL('../assets/Images/Iphone2.svg', import.meta.url).href,
    IphoneView: new URL('../assets/Images/IphoneView.svg', import.meta.url).href,
    Pen: new URL('../assets/Images/Pen.svg', import.meta.url).href,
    Bin: new URL('../assets/Images/Bin.svg', import.meta.url).href,
    Ban: new URL('../assets/Images/Ban.svg', import.meta.url).href,
    Select: new URL('../assets/Images/Select.svg', import.meta.url).href,
    Delete: new URL('../assets/Images/Delete.svg', import.meta.url).href,
    MenuDropdown: new URL('../assets/Images/menuDropdown.svg', import.meta.url).href,
    WhiteBox: new URL('../assets/Images/WhiteBox.svg', import.meta.url).href,
    dollar: new URL('../assets/Images/dollar.svg', import.meta.url).href,
    Tag: new URL('../assets/Images/Tag.svg', import.meta.url).href,
    Sales: new URL('../assets/Images/Sales.svg', import.meta.url).href,
    RegectedSale: new URL('../assets/Images/regectedSale.svg', import.meta.url).href,
    Volume: new URL('../assets/Images/Volume.svg', import.meta.url).href,
    Admin: new URL('../assets/Images/Admin.svg', import.meta.url).href,
    Upload: new URL('../assets/Images/Upload.svg', import.meta.url).href,
    Filter: new URL('../assets/Images/Filter.svg', import.meta.url).href,
    RectangleBox: new URL('../assets/Images/RectangleBox.svg', import.meta.url).href,
    Search: new URL('../assets/Images/Search.svg', import.meta.url).href,
    FilterDate: new URL('../assets/Images/FilterDate.svg', import.meta.url).href,
    Guy1: new URL('../assets/Images/Guy1.svg', import.meta.url).href,
    Guy2: new URL('../assets/Images/Guy2.svg', import.meta.url).href,
    Guy3: new URL('../assets/Images/Guy3.svg', import.meta.url).href,
    newmembers: new URL('../assets/Images/newmembers.svg', import.meta.url).href,
    Rolesbadge: new URL('../assets/Images/Rolesbadge.svg', import.meta.url).href,

    AtmBackground: new URL('../assets/Images/Atm-background.svg', import.meta.url).href,
    Coins: new URL('../assets/Images/coins.svg', import.meta.url).href,
    Laughingadmin: new URL('../assets/Images/Laughingadmin.svg', import.meta.url).href,
    // 
    // 
    // 
    // ICONS BELOW HERREEEEE
    // 
    // 
    // 
    New: new URL('../assets/icons/New.svg', import.meta.url).href,
    Person: new URL('../assets/icons/Person.svg', import.meta.url).href,
    bluetick: new URL('../assets/icons/bluetick.svg', import.meta.url).href,
    greencross: new URL('../assets/icons/greencross.svg', import.meta.url).href,
    personicon: new URL('../assets/icons/personicon.svg', import.meta.url).href,
    ProductBox: new URL('../assets/icons/ProductBox.svg', import.meta.url).href,
    CashWithdraw: new URL('../assets/icons/cashWithdraw.svg', import.meta.url).href,
    DollorHouse: new URL('../assets/icons/DollorHouse.svg', import.meta.url).href,
    dropdown: new URL('../assets/icons/dropdown.svg', import.meta.url).href,
    Eyesclosed: new URL('../assets/icons/Eyesclosed.svg', import.meta.url).href,
    deleteproduct: new URL('../assets/icons/deleteproduct.svg', import.meta.url).href,
    Key: new URL('../assets/icons/Key.svg', import.meta.url).href,
    Loginarrow: new URL('../assets/icons/Loginarrow.svg', import.meta.url).href,
    Logoutarrow: new URL('../assets/icons/Logoutarrow.svg', import.meta.url).href,
    Editpen: new URL('../assets/icons/Editpen.svg', import.meta.url).href,
    Percentage: new URL('../assets/icons/Percentage.svg', import.meta.url).href,
    Cross: new URL('../assets/icons/cross.svg', import.meta.url).href,
    Edit: new URL('../assets/icons/Edit.svg', import.meta.url).href,
    Password: new URL('../assets/icons/Password.svg', import.meta.url).href,
    Phone: new URL('../assets/icons/Phone.svg', import.meta.url).href,
    Bank: new URL('../assets/icons/Bank.svg', import.meta.url).href,
    BankHome: new URL('../assets/icons/BankHome.svg', import.meta.url).href,
    Bell: new URL('../assets/icons/Bell.svg', import.meta.url).href,
    Shield: new URL('../assets/icons/shield.svg', import.meta.url).href,
    Maintenance: new URL('../assets/icons/Maintenance.svg', import.meta.url).href,
    AddItem: new URL('../assets/icons/Add.svg', import.meta.url).href,
    Flag: new URL('../assets/icons/Flag.svg', import.meta.url).href,
    pending: new URL('../assets/icons/pending.svg', import.meta.url).href,
    Ring: new URL('../assets/icons/Ring.svg', import.meta.url).href,
    Send: new URL('../assets/icons/Send.svg', import.meta.url).href,
    Csvicon: new URL('../assets/icons/Csvicon.svg', import.meta.url).href,
}
export default IMAGES